# Python essencial para agentes de IA

## Workshop gratuito - Outspoken Market

https://www.outspokenmarket.com/omnp

Este notebook foi criado para quem nunca viu Python antes, mas quer entender as peças essenciais que aparecem dentro de um agente de IA.

Nesta aula, **não vamos construir o agente completo ainda**.  
O objetivo é aprender os fundamentos de Python que depois serão usados para montar um agente com:

- entrada do usuário
- decisões simples
- funções como ferramentas
- arquivos de contexto
- JSON
- análise de dados com CSV
- validação para evitar erros

A ideia central da aula é:

> Um agente de IA não é apenas um modelo respondendo texto.  
> Um agente precisa organizar contexto, escolher ações, executar ferramentas e validar resultados.

## 0. Como usar este notebook no Google Colab

No Colab, cada bloco de código pode ser executado separadamente.

Para executar uma célula:

1. Clique na célula de código.
2. Aperte `Shift + Enter`.
3. Observe o resultado abaixo da célula.

Durante a aula, execute os blocos na ordem.

In [6]:
# Nosso primeiro comando em Python.
# A função print() mostra uma mensagem na tela.


print("Hello, AI agents!")

Hello, AI agents!

# 1. Variáveis: guardando informações

Uma variável é um nome que guarda um valor.

Dentro de um agente, variáveis podem guardar coisas como:

- a pergunta do usuário
- o nome de um arquivo
- a ferramenta escolhida
- os argumentos que serão usados por uma função

In [18]:
# Criando variáveis simples.

name = "Leandro"
file_name = "sales.csv"
user_request = "show me the sales per product"

print(name)
print(file_name)
print(user_request)

Leandro
sales.csv
show me the sales per product

## 1.1 Tipos básicos de dados

Os tipos mais importantes para esta aula são:

- `str`: texto
- `int`: número inteiro
- `float`: número decimal
- `bool`: verdadeiro ou falso

In [20]:
# Exemplos de tipos básicos.

user_name = "Ana"          # str: texto
units_sold = 10            # int: número inteiro
price = 49.90              # float: número decimal
is_active = True           # bool: verdadeiro ou falso

print(user_name)
print(units_sold)
print(price)
print(is_active)

# A função type() mostra o tipo de uma variável.
print(type(user_name))
print(type(units_sold))
print(type(price))
print(type(is_active))

Ana
10
49.9
True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

## 1.2 Por que variáveis importam para agentes?

Imagine que o usuário escreveu:

> "show me the sales per product"

O agente precisa guardar essa frase, interpretar o pedido e decidir o que fazer com ela.

In [23]:
# Guardando uma solicitação do usuário.

user_request = "show me the sales per product"

print("User request:")
print(user_request)

User request:
show me the sales per product

# 2. Strings: trabalhando com texto

A maior parte da interação com um agente começa como texto.

Por isso, precisamos saber manipular strings.

In [24]:
# Exemplo de string.

text = "List the distinct products"

print(text)

List the distinct products

## 2.1 Convertendo texto para minúsculas

Quando queremos comparar textos, é comum converter tudo para minúsculas.

Assim, evitamos erros entre `"List"`, `"list"` e `"LIST"`.

In [25]:
user_request = "List the distinct products"

# lower() transforma o texto em minúsculas.
text = user_request.lower()

print(text)

list the distinct products

## 2.2 Verificando se uma palavra existe no texto

O operador `in` permite testar se uma palavra ou expressão aparece dentro de uma string.

Isso é muito útil para decisões simples.

In [28]:
user_request = "List the distinct products"
text = user_request.lower()

print("distinct products" in text)
print("list" in text)
print("count" in text)

True
True
False

## 2.3 Exemplo conectado a agentes

Antes de chamar um LLM, podemos usar Python para identificar intenções óbvias.

In [38]:
user_request = "List the distinct products"
text = user_request.lower()

if "distinct products" in text and "list" in text:
    print("The user wants to list distinct products.")

The user wants to list distinct products.

# 3. Condicionais: ensinando o código a decidir

Condicionais permitem que o programa tome decisões.

Essa lógica aparece diretamente em roteadores determinísticos de agentes.

In [46]:
def logical_and(a, b):
    return a and b

def logical_or(a, b):
    return a or b

# Variáveis booleanas
variables = [True, False]

print("### Tabela Verdade para AND (E) ###")
print("| A     | B     | A AND B |")
print("|-------|-------|---------|")
for a in variables:
    for b in variables:
        result = logical_and(a, b)
        print(f"| {str(a):<5} | {str(b):<5} | {str(result):<7} |")

print("\n### Tabela Verdade para OR (OU) ###")
print("| A     | B     | A OR B  |")
print("|-------|-------|---------|")
for a in variables:
    for b in variables:
        result = logical_or(a, b)
        print(f"| {str(a):<5} | {str(b):<5} | {str(result):<7} |")

### Tabela Verdade para AND (E) ###
| A     | B     | A AND B |
|-------|-------|---------|
| True  | True  | True    |
| True  | False | False   |
| False | True  | False   |
| False | False | False   |

### Tabela Verdade para OR (OU) ###
| A     | B     | A OR B  |
|-------|-------|---------|
| True  | True  | True    |
| True  | False | True    |
| False | True  | True    |
| False | False | False   |

In [52]:
# Exemplo simples com if, elif e else.

user_request = "count the number of distinct products"
text = user_request.lower()

if "distinct products" in text and "list" in text:
    print("Use list_distinct_csv")
elif "distinct products" in text and ("count" in text or "number" in text):
    print("Use count_distinct_csv")
else:
    print("Ask the LLM")

Use count_distinct_csv

## 3.1 A ordem das regras importa

Duas frases podem parecer parecidas, mas pedir coisas diferentes:

- `"count the number of distinct products"` pede uma contagem
- `"list the distinct products"` pede uma lista

Em agentes, uma regra mal ordenada pode mandar o pedido para a ferramenta errada.

In [53]:
# Teste 1: contar produtos distintos.

user_request = "count the number of distinct products"
text = user_request.lower()

if "distinct products" in text and ("list" in text or "show" in text):
    print("Use list_distinct_csv")
elif "distinct products" in text and ("count" in text or "number" in text):
    print("Use count_distinct_csv")
else:
    print("Ask the LLM")

Use count_distinct_csv

In [54]:
# Teste 2: listar produtos distintos.

user_request = "list the distinct products"
text = user_request.lower()

if "distinct products" in text and ("list" in text or "show" in text):
    print("Use list_distinct_csv")
elif "distinct products" in text and ("count" in text or "number" in text):
    print("Use count_distinct_csv")
else:
    print("Ask the LLM")

Use list_distinct_csv

## 3.2 Mensagem importante

Nem tudo precisa ir para o modelo de IA.

Quando a intenção é óbvia, Python pode decidir diretamente.

# 4. Listas: guardando vários itens

Uma lista guarda vários valores.

Em Python, listas usam colchetes `[]`.

In [61]:
# Criando uma lista de produtos.

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

print(products)

['Laptop', 'Phone', 'Tablet', 'Phone', 'Laptop']

In [68]:
# Acessando itens da lista.
# Em Python, a contagem começa em zero.

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

print(products[0])
print(products[1])
print(products[2])

Laptop
Phone
Tablet

In [69]:
# len() mostra quantos itens existem na lista.

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

print(len(products))

5

## 4.1 Valores únicos com set()

Se quisermos remover repetições, podemos usar `set()`.

Depois, podemos usar `sorted()` para ordenar o resultado.

In [71]:
products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

unique_products = sorted(set(products))

print(unique_products)

['Laptop', 'Phone', 'Tablet']

## 4.2 Conexão com agentes

Quando o usuário pergunta:

> "list the distinct products"

O agente precisa fazer algo parecido:

1. pegar a coluna `product`
2. remover duplicatas
3. ordenar
4. devolver o resultado

# 5. Dicionários: a estrutura mais importante para agentes

Dicionários guardam pares de chave e valor.

Eles são essenciais para agentes porque permitem representar decisões estruturadas.

In [77]:
# Um dicionário simples.

person = {
    "name": "Ana",
    "role": "student",
    "active": True
}

print(person)
print(person["name"])
print(person["role"])

{'name': 'Ana', 'role': 'student', 'active': True}
Ana
student

## 5.1 Uma decisão de agente como dicionário

Um agente pode transformar a pergunta do usuário em algo assim:

```python
{
    "tool": "list_distinct_csv",
    "args": {
        "filename": "sales.csv",
        "column": "product"
    }
}
```

Isso significa:

- `tool`: qual função executar
- `args`: quais argumentos passar para a função

In [78]:
decision = {
    "tool": "list_distinct_csv",
    "args": {
        "filename": "sales.csv",
        "column": "product"
    }
}

print(decision)
print(decision["tool"])
print(decision["args"])
print(decision["args"]["column"])

{'tool': 'list_distinct_csv', 'args': {'filename': 'sales.csv', 'column': 'product'}}
list_distinct_csv
{'filename': 'sales.csv', 'column': 'product'}
product

## 5.2 Usando `.get()`

Quando não temos certeza se uma chave existe, podemos usar `.get()`.

Isso evita alguns erros.

In [82]:
decision = {
    "tool": "list_distinct_csv",
    "args": {
        "filename": "sales.csv",
        "column": "product"
    }
}

# A chave "limit" não existe.
# Com get(), podemos definir um valor padrão.
limit = decision["args"].get("limit", "erro")

print(limit)

erro

## 5.3 Mensagem central

Um agente de IA precisa converter linguagem natural em uma decisão estruturada.

O dicionário é uma das formas mais simples de representar isso em Python.

# 6. Funções: transformando código em tools

Funções permitem empacotar uma ação com nome, parâmetros e resultado.

Em um agente, uma tool é basicamente uma função Python que o sistema pode chamar.

In [95]:
# Função simples.

def greet(name):
    return f"Hello, {name}!"

print(greet("Leandro"))
print(greet("Ana"))

Hello, Leandro!
Hello, Ana!

## 6.1 Parâmetros e retorno

Uma função pode receber parâmetros e devolver um resultado com `return`.

Vamos criar uma função que lista valores distintos.

In [98]:
def list_distinct_values(values):
    # set(values) remove duplicatas.
    # sorted() ordena os valores.
    unique_values = sorted(set(values))
    return unique_values

In [100]:
products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop", "Borrosca"]

result = list_distinct_values(products)

print(result)

['Borrosca', 'Laptop', 'Phone', 'Tablet']

## 6.2 Função que retorna texto formatado

Em agentes, normalmente queremos devolver uma resposta em texto.

In [107]:
def list_distinct_values_as_text(values):
    unique_values = sorted(set(values))

    # "\n".join(...) junta os itens colocando uma quebra de linha entre eles.
    return "Distinct values:\n" + "\n".join(unique_values)

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop", "Borrosca"]

print(list_distinct_values_as_text(products))

Distinct values:
Borrosca
Laptop
Phone
Tablet

## 6.3 Docstrings

Uma docstring é um texto dentro da função explicando o que ela faz.

Isso ajuda humanos e também ajuda a documentar ferramentas de agentes.

In [108]:
def count_distinct_values(values):
    """
    Counts the number of distinct values in a list.
    """
    return len(set(values))

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

print(count_distinct_values(products))

3

## 6.4 Simulando um pequeno registro de tools

Um agente precisa saber quais funções estão disponíveis.

Podemos registrar funções em um dicionário chamado `TOOLS`.

In [109]:
def list_distinct_values(values):
    """
    Lists distinct values.
    """
    return sorted(set(values))

def count_distinct_values(values):
    """
    Counts distinct values.
    """
    return len(set(values))

TOOLS = {
    "list_distinct_values": list_distinct_values,
    "count_distinct_values": count_distinct_values
}

print(TOOLS.keys())

dict_keys(['list_distinct_values', 'count_distinct_values'])

In [111]:
# Chamando uma função pelo nome salvo no dicionário TOOLS.

products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

prompt = "count_distinct_values"

tool_function = TOOLS[prompt]

result = tool_function(products)

print(result)

3

## 6.5 Conexão com agentes

Essa é uma das ideias mais importantes do workshop:

> O LLM escolhe o nome da tool.  
> O Python procura essa tool no dicionário.  
> O Python executa a função.

Essa separação deixa o sistema mais seguro e organizado.

# 7. Arquivos no Colab: criando e lendo contexto

Agentes modernos muitas vezes usam arquivos como contexto.

Por exemplo:

- `IDENTITY.md`
- `PROJECT_CONTEXT.md`
- `REFERENCES.md`

Esses arquivos explicam quem é o agente, qual é o projeto e quais regras devem ser consideradas.

In [112]:
# Criando um arquivo de contexto no Colab.

context = '''
# Project Context

This agent works with a sales dataset.
The main file is sales.csv.
The agent should avoid inventing columns.
'''

with open("PROJECT_CONTEXT.md", "w", encoding="utf-8") as file:
    file.write(context)

print("File created.")

File created.

In [113]:
# Lendo o arquivo que acabamos de criar.

with open("PROJECT_CONTEXT.md", "r", encoding="utf-8") as file:
    content = file.read()

print(content)

# Project Context

This agent works with a sales dataset.
The main file is sales.csv.
The agent should avoid inventing columns.

## 7.1 Usando pathlib

`pathlib` é uma forma moderna de trabalhar com arquivos e pastas em Python.

Ela será muito útil quando o agente precisar procurar arquivos em um workspace.

In [115]:
from pathlib import Path

caminho = Path("PROJECT_CONTEXT.md")

print(caminho.exists())
print(caminho.name)
print(caminho.read_text(encoding="utf-8"))

True
PROJECT_CONTEXT.md

# Project Context

This agent works with a sales dataset.
The main file is sales.csv.
The agent should avoid inventing columns.

## 7.2 Criando uma pasta de trabalho

Em um agente local, podemos ter uma pasta controlada para arquivos.

Por exemplo:

```text
agent_files/
```

Vamos criar essa pasta no Colab.

In [118]:
from pathlib import Path

workspace = Path("agent_files")
workspace.mkdir(exist_ok=True)

print("Workspace created:", workspace.exists())

Workspace created: True

In [119]:
# Criando alguns arquivos de exemplo dentro da pasta agent_files.

(workspace / "notes.txt").write_text("These are some notes.", encoding="utf-8")
(workspace / "todo.txt").write_text("Build an AI agent later.", encoding="utf-8")

print("Files created.")

Files created.

In [124]:
workspace = Path("agent_files")

In [125]:
# Listando os arquivos dentro da pasta.

for file in workspace.iterdir():
    print(file.name)

todo.txt
notes.txt

## 7.3 Conexão com agentes

Arquivos e pastas permitem organizar contexto.

A lógica é:

- o usuário trabalha em um projeto
- o projeto tem arquivos
- o agente lê esses arquivos
- o agente responde melhor porque sabe o contexto

# 8. JSON: a ponte entre LLM e Python

Modelos de IA respondem em texto.

Mas um agente precisa transformar esse texto em uma estrutura que Python consiga executar.

JSON é um formato muito usado para isso.

In [126]:
import json

# Isto é uma string em formato JSON.
response = '{"tool": "list_distinct_values", "args": {"column": "product"}}'

print(response)
print(type(response))

{"tool": "list_distinct_values", "args": {"column": "product"}}
<class 'str'>

In [127]:
# json.loads() transforma a string JSON em um dicionário Python.

response = '{"tool": "list_distinct_values", "args": {"column": "product"}}'

decision = json.loads(response)

print(decision)
print(type(decision))
print(decision["tool"])
print(decision["args"])

{'tool': 'list_distinct_values', 'args': {'column': 'product'}}
<class 'dict'>
list_distinct_values
{'column': 'product'}

## 8.1 Simulando uma decisão de agente

Vamos simular uma decisão que veio de um modelo.

O Python vai ler a decisão e executar a função correta.

In [128]:
# Criamos algumas funções.

def list_distinct_values(values):
    return sorted(set(values))

def count_distinct_values(values):
    return len(set(values))

# Registramos as funções como tools.
TOOLS = {
    "list_distinct_values": list_distinct_values,
    "count_distinct_values": count_distinct_values
}

# Esta seria a decisão estruturada do modelo.
decision_json = '{"tool": "list_distinct_values", "args": {}}'

# Transformamos JSON em dicionário.
decision = json.loads(decision_json)

# Dados de exemplo.
products = ["Laptop", "Phone", "Tablet", "Phone", "Laptop"]

# Pegamos o nome da tool.
tool_name = decision["tool"]

# Buscamos a função.
tool_function = TOOLS[tool_name]

# Executamos.
result = tool_function(products)

print(result)

['Laptop', 'Phone', 'Tablet']

## 8.2 Tratando JSON inválido

Às vezes, um modelo pode devolver um texto que não é JSON válido.

Um agente robusto precisa lidar com isso.

In [130]:
import json

bad_response = "this is not valid json"

try:
    decision = json.loads(bad_response)
    print(decision)
except json.JSONDecodeError:
    print("Invalid JSON. Falling back to a safe response.")

Puts deu boxsta

# 9. Pandas mínimo: trabalhando com sales.csv

Agora vamos trabalhar com dados.

`pandas` é uma biblioteca muito usada para ler e analisar tabelas.

No nosso caso, vamos criar um arquivo `sales.csv` no próprio Colab.

In [131]:
import pandas as pd

# Criando dados de exemplo.
# Cada chave do dicionário será uma coluna.
data = {
    "date": [
        "2026-01-01", "2026-01-01", "2026-01-02", "2026-01-02",
        "2026-01-03", "2026-01-03", "2026-01-04", "2026-01-04"
    ],
    "region": [
        "US", "Europe", "US", "Asia",
        "Europe", "Asia", "US", "Europe"
    ],
    "product": [
        "Laptop", "Phone", "Laptop", "Tablet",
        "Notebook", "Phone", "Tablet", "Laptop"
    ],
    "units_sold": [
        10, 20, 15, 8,
        12, 18, 7, 9
    ],
    "price": [
        1200, 800, 1200, 600,
        900, 800, 600, 1200
    ],
    "revenue": [
        12000, 16000, 18000, 4800,
        10800, 14400, 4200, 10800
    ]
}

df = pd.DataFrame(data)

# Salvando como CSV.
df.to_csv("sales.csv", index=False)

# Mostrando o DataFrame.
df

         date  region   product  units_sold  price  revenue
0  2026-01-01      US    Laptop          10   1200    12000
1  2026-01-01  Europe     Phone          20    800    16000
2  2026-01-02      US    Laptop          15   1200    18000
3  2026-01-02    Asia    Tablet           8    600     4800
4  2026-01-03  Europe  Notebook          12    900    10800
5  2026-01-03    Asia     Phone          18    800    14400
6  2026-01-04      US    Tablet           7    600     4200
7  2026-01-04  Europe    Laptop           9   1200    10800

## 9.1 Lendo um CSV

Agora vamos ler o arquivo `sales.csv`.

In [132]:
import pandas as pd

df = pd.read_csv("sales.csv")

df

         date  region   product  units_sold  price  revenue
0  2026-01-01      US    Laptop          10   1200    12000
1  2026-01-01  Europe     Phone          20    800    16000
2  2026-01-02      US    Laptop          15   1200    18000
3  2026-01-02    Asia    Tablet           8    600     4800
4  2026-01-03  Europe  Notebook          12    900    10800
5  2026-01-03    Asia     Phone          18    800    14400
6  2026-01-04      US    Tablet           7    600     4200
7  2026-01-04  Europe    Laptop           9   1200    10800

## 9.2 Visualizando as primeiras linhas

`head()` mostra as primeiras linhas da tabela.

In [143]:
df.head(2)

         date  region product  units_sold  price  revenue
0  2026-01-01      US  Laptop          10   1200    12000
1  2026-01-01  Europe   Phone          20    800    16000

## 9.3 Listando colunas

`df.columns` mostra os nomes das colunas.

Isso é essencial para evitar que o agente invente nomes de colunas.

In [137]:
df.columns

Index(['date', 'region', 'product', 'units_sold', 'price', 'revenue'], dtype='object')

In [138]:
# Transformando as colunas em uma lista.

columns = df.columns.tolist()

print(columns)

['date', 'region', 'product', 'units_sold', 'price', 'revenue']

In [140]:
columns[3]

'units_sold'

## 9.4 Estatísticas descritivas

`describe()` mostra estatísticas básicas das colunas numéricas.

Com `include="all"`, também traz informações sobre colunas de texto.

In [144]:
df.describe()

       units_sold        price       revenue
count    8.000000     8.000000      8.000000
mean    12.375000   912.500000  11375.000000
std      4.808846   258.774585   4930.879377
min      7.000000   600.000000   4200.000000
25%      8.750000   750.000000   9300.000000
50%     11.000000   850.000000  11400.000000
75%     15.750000  1200.000000  14800.000000
max     20.000000  1200.000000  18000.000000

In [145]:
df.describe(include="all")

              date region product  units_sold        price       revenue
count            8      8       8    8.000000     8.000000      8.000000
unique           4      3       4         NaN          NaN           NaN
top     2026-01-01     US  Laptop         NaN          NaN           NaN
freq             2      3       3         NaN          NaN           NaN
mean           NaN    NaN     NaN   12.375000   912.500000  11375.000000
std            NaN    NaN     NaN    4.808846   258.774585   4930.879377
min            NaN    NaN     NaN    7.000000   600.000000   4200.000000
25%            NaN    NaN     NaN    8.750000   750.000000   9300.000000
50%            NaN    NaN     NaN   11.000000   850.000000  11400.000000
75%            NaN    NaN     NaN   15.750000  1200.000000  14800.000000
max            NaN    NaN     NaN   20.000000  1200.000000  18000.000000

## 9.5 Trabalhando com uma coluna

Podemos selecionar uma coluna usando:

```python
df["product"]
```

In [146]:
df["product"]

0      Laptop
1       Phone
2      Laptop
3      Tablet
4    Notebook
5       Phone
6      Tablet
7      Laptop
Name: product, dtype: object

In [148]:
df

         date  region   product  units_sold  price  revenue
0  2026-01-01      US    Laptop          10   1200    12000
1  2026-01-01  Europe     Phone          20    800    16000
2  2026-01-02      US    Laptop          15   1200    18000
3  2026-01-02    Asia    Tablet           8    600     4800
4  2026-01-03  Europe  Notebook          12    900    10800
5  2026-01-03    Asia     Phone          18    800    14400
6  2026-01-04      US    Tablet           7    600     4200
7  2026-01-04  Europe    Laptop           9   1200    10800

In [151]:
df.iloc[3]

date          2026-01-02
region              Asia
product           Tablet
units_sold             8
price                600
revenue             4800
Name: 3, dtype: object

In [152]:
# Valores únicos da coluna product.

df["product"].unique()

array(['Laptop', 'Phone', 'Tablet', 'Notebook'], dtype=object)

In [153]:
# Número de valores únicos da coluna product.

df["product"].nunique()

4

## 9.6 Agrupando dados

Uma das operações mais importantes em análise de dados é agrupar.

Exemplo:

> Qual é a receita total por produto?

In [159]:
# Receita total por produto.

df.groupby("product")["revenue"].sum()

product
Laptop      40800
Notebook    10800
Phone       30400
Tablet       9000
Name: revenue, dtype: int64

## 9.7 Agrupando por mais de uma coluna

Agora uma pergunta mais detalhada:

> Qual é a receita total por produto e região?

In [161]:
# Receita total por produto e região.

df.groupby(["region", "product"])["revenue"].sum()

region  product
Asia    Phone       14400
        Tablet       4800
Europe  Laptop      10800
        Notebook    10800
        Phone       16000
US      Laptop      30000
        Tablet       4200
Name: revenue, dtype: int64

In [162]:
# Versão mais bonita para visualização.

result = df.groupby(["product", "region"])["revenue"].sum().reset_index()

result

    product  region  revenue
0    Laptop  Europe    10800
1    Laptop      US    30000
2  Notebook  Europe    10800
3     Phone    Asia    14400
4     Phone  Europe    16000
5    Tablet    Asia     4800
6    Tablet      US     4200

## 9.8 Média de vendas por produto e região

Agora vamos calcular a média de receita por produto e região.

In [163]:
average_sales = df.groupby(["product", "region"])["revenue"].mean().reset_index()

average_sales

    product  region  revenue
0    Laptop  Europe  10800.0
1    Laptop      US  15000.0
2  Notebook  Europe  10800.0
3     Phone    Asia  14400.0
4     Phone  Europe  16000.0
5    Tablet    Asia   4800.0
6    Tablet      US   4200.0

## 9.9 Ordenando resultados

Muitas perguntas de negócio usam palavras como:

- top
- maior
- melhor
- ranking
- ordenar

Para isso usamos `sort_values()`.

In [166]:
# Receita total por produto, ordenada da maior para a menor.

sales_per_product = df.groupby("product")["revenue"].sum().reset_index()

sales_per_product = sales_per_product.sort_values("revenue", ascending=False)

sales_per_product

    product  revenue
0    Laptop    40800
2     Phone    30400
1  Notebook    10800
3    Tablet     9000

## 9.10 Limitando resultados

Às vezes queremos apenas os top 3 resultados.

In [167]:
top_3_products = sales_per_product.head(3)

top_3_products

    product  revenue
0    Laptop    40800
2     Phone    30400
1  Notebook    10800

# 10. Validação e normalização

Um agente bom não deve confiar cegamente no modelo.

Se o modelo sugerir uma coluna que não existe, Python precisa validar.

Exemplo:

- usuário diz: `"total sales"`
- a coluna real no CSV é: `"revenue"`

Precisamos mapear linguagem de negócio para o nome real da coluna.

In [168]:
df

         date  region   product  units_sold  price  revenue
0  2026-01-01      US    Laptop          10   1200    12000
1  2026-01-01  Europe     Phone          20    800    16000
2  2026-01-02      US    Laptop          15   1200    18000
3  2026-01-02    Asia    Tablet           8    600     4800
4  2026-01-03  Europe  Notebook          12    900    10800
5  2026-01-03    Asia     Phone          18    800    14400
6  2026-01-04      US    Tablet           7    600     4200
7  2026-01-04  Europe    Laptop           9   1200    10800

In [170]:
# Lista de colunas permitidas.

allowed_columns = df.columns.tolist()

column = "total_sales"

if column in allowed_columns:
    print("Column exists.")
else:
    print("Column not found.")

Column not found.

## 10.1 Normalizando nomes de colunas

Vamos criar uma função para mapear termos comuns para nomes reais do dataset.

In [172]:
def normalize_column_name(column):
    """
    Maps natural language column references to real column names.
    """
    if column is None:
        return column

    # Padroniza o texto.
    normalized = column.strip().lower().replace(" ", "_")

    # Mapeia nomes comuns para nomes reais.
    aliases = {
        "sales": "revenue",
        "total_sales": "revenue",
        "sales_amount": "revenue",
        "total_revenue": "revenue",
        "units": "units_sold",
        "units_sold": "units_sold",
        "units_sold_per_product": "units_sold",
        "quantity": "units_sold",
        "product_name": "product",
        "item": "product"
    }

    return aliases.get(normalized, normalized)

print(normalize_column_name("total sales"))
print(normalize_column_name("sales"))
print(normalize_column_name("units sold"))
print(normalize_column_name("item"))

revenue
revenue
units_sold
product

## 10.2 Validando depois de normalizar

Agora podemos normalizar primeiro e validar depois.

In [173]:
allowed_columns = ["date", "region", "product", "units_sold", "price", "revenue"]

user_column = "total sales"

column = normalize_column_name(user_column)

if column in allowed_columns:
    print("Column exists:", column)
else:
    print("Column not found:", column)

Column exists: revenue

## 10.3 Criando uma função segura para agregar dados

Vamos criar uma função simples que:

1. recebe uma coluna de agrupamento
2. recebe uma coluna numérica
3. recebe uma operação
4. valida tudo
5. executa o cálculo

In [ ]:
def simple_groupby(df, group_by, target_column, operation):
    """
    Groups a DataFrame by one column and aggregates a target column.
    This is a simplified version of a data tool used by an agent.
    """
    allowed_operations = ["sum", "mean", "count", "min", "max", "median"]

    # Normaliza nomes de colunas.
    group_by = normalize_column_name(group_by)
    target_column = normalize_column_name(target_column)

    # Valida se as colunas existem.
    if group_by not in df.columns:
        return f"Column not found: {group_by}"

    if target_column not in df.columns:
        return f"Column not found: {target_column}"

    # Valida a operação.
    if operation not in allowed_operations:
        return f"Invalid operation: {operation}"

    # Executa a agregação.
    result = df.groupby(group_by)[target_column].agg(operation).reset_index()

    return result

simple_groupby(df, group_by="product", target_column="total sales", operation="sum")

## 10.4 Agrupando por múltiplas colunas

Clientes podem pedir combinações diferentes, por exemplo:

- receita por produto
- receita por região
- receita por produto e região

Para isso, podemos permitir que `group_by` seja uma lista.

In [174]:
def flexible_groupby(df, group_by, target_column, operation):
    """
    Groups a DataFrame by one or more columns and aggregates a target column.
    This is closer to what a real agent tool would need.
    """
    allowed_operations = ["sum", "mean", "count", "min", "max", "median"]

    # Se group_by for texto, transformamos em lista.
    if isinstance(group_by, str):
        group_by = [group_by]

    # Normaliza todos os nomes de agrupamento.
    group_by = [normalize_column_name(col) for col in group_by]

    # Normaliza a coluna alvo.
    target_column = normalize_column_name(target_column)

    # Valida colunas de agrupamento.
    for col in group_by:
        if col not in df.columns:
            return f"Column not found: {col}"

    # Valida coluna alvo.
    if target_column not in df.columns:
        return f"Column not found: {target_column}"

    # Valida operação.
    if operation not in allowed_operations:
        return f"Invalid operation: {operation}"

    # Executa a agregação.
    result = df.groupby(group_by)[target_column].agg(operation).reset_index()

    return result

In [175]:
df

         date  region   product  units_sold  price  revenue
0  2026-01-01      US    Laptop          10   1200    12000
1  2026-01-01  Europe     Phone          20    800    16000
2  2026-01-02      US    Laptop          15   1200    18000
3  2026-01-02    Asia    Tablet           8    600     4800
4  2026-01-03  Europe  Notebook          12    900    10800
5  2026-01-03    Asia     Phone          18    800    14400
6  2026-01-04      US    Tablet           7    600     4200
7  2026-01-04  Europe    Laptop           9   1200    10800

In [180]:
flexible_groupby(
    df,
    group_by=[ "region"],
    target_column="total sales",
    operation="sum"
)

   region  revenue
0    Asia    19200
1  Europe    37600
2      US    34200

# 11. Juntando as peças: uma mini-simulação de agente

Ainda não vamos construir o agente completo.

Mas já podemos simular o fluxo mental:

1. usuário faz um pedido
2. Python tenta resolver pedidos óbvios
3. caso contrário, uma decisão estruturada seria gerada
4. a função correta é executada
5. o resultado é devolvido

In [ ]:
# Tools disponíveis para a mini-simulação.

def list_distinct_products():
    values = sorted(set(df["product"]))
    return "Distinct products:\n" + "\n".join(values)

def count_distinct_products():
    count = df["product"].nunique()
    return f"Number of distinct products: {count}"

TOOLS = {
    "list_distinct_products": list_distinct_products,
    "count_distinct_products": count_distinct_products
}

def deterministic_route(user_input):
    """
    Simple deterministic router.
    It handles obvious requests without using an LLM.
    """
    text = user_input.lower().strip()

    if "distinct products" in text and ("list" in text or "show" in text):
        return {
            "tool": "list_distinct_products",
            "args": {}
        }

    if "distinct products" in text and ("count" in text or "number" in text):
        return {
            "tool": "count_distinct_products",
            "args": {}
        }

    return None

def run_mini_agent(user_input):
    """
    Runs a very small simulation of an agent.
    """
    decision = deterministic_route(user_input)

    if decision is None:
        return "This request would be sent to the LLM in the full agent."

    tool_name = decision["tool"]
    args = decision["args"]

    if tool_name not in TOOLS:
        return f"Tool not found: {tool_name}"

    tool_function = TOOLS[tool_name]

    return tool_function(**args)

print(run_mini_agent("list the distinct products"))
print()
print(run_mini_agent("count the number of distinct products"))
print()
print(run_mini_agent("show me the sales per product"))

## 11.1 Mini-simulação com JSON

Agora vamos simular uma decisão em JSON.

Essa é a forma que um LLM poderia responder em um agente real.

In [ ]:
import json

decision_json = '''
{
    "tool": "count_distinct_products",
    "args": {}
}
'''

decision = json.loads(decision_json)

tool_name = decision["tool"]
args = decision["args"]

result = TOOLS[tool_name](**args)

print(result)

# 12. Como tudo isso vira um agente de IA

Agora podemos conectar cada conceito da aula com uma peça do agente real.

| Conceito de Python | Papel dentro do agente |
|---|---|
| Variáveis | Guardam input, arquivo ativo, nome da tool e parâmetros |
| Strings | Representam pedidos do usuário |
| Condicionais | Criam roteamento determinístico |
| Listas | Guardam colunas, arquivos, resultados e grupos |
| Dicionários | Representam decisões estruturadas |
| Funções | Viram tools |
| Arquivos | Guardam contexto do projeto |
| JSON | Faz a ponte entre LLM e Python |
| Pandas | Executa análise de dados |
| Validação | Impede erros e invenções do modelo |

## 12.1 Fluxo final

Este é o fluxo que vamos construir na próxima aula:

```text
Usuário
   ↓
agent.py
   ↓
prompt + contexto
   ↓
LLM escolhe uma tool
   ↓
Python valida a decisão
   ↓
tools.py executa a função
   ↓
resultado volta para o usuário
```

A mensagem principal é:

> O modelo decide.  
> O Python valida.  
> A tool executa.

# 13. Exercícios para os alunos

Use estes exercícios para praticar depois da aula.

## Exercício 1

Crie uma variável chamada `user_request` com o texto:

```text
show me the revenue per region
```

Converta para minúsculas usando `.lower()`.

## Exercício 2

Crie uma lista com produtos repetidos e mostre apenas os valores únicos.

## Exercício 3

Crie um dicionário representando esta decisão:

```json
{
  "tool": "describe_column",
  "args": {
    "filename": "sales.csv",
    "column": "product"
  }
}
```

## Exercício 4

Crie uma função chamada `count_items(values)` que retorna quantos itens existem em uma lista.

## Exercício 5

Use pandas para calcular a receita total por região.

## Exercício 6

Modifique a função `flexible_groupby()` para testar outra operação, como `mean` ou `max`.

# 14. Fechamento

Você não precisa aprender Python inteiro para começar a entender agentes de IA.

Para sair do zero, você precisa entender:

- variáveis
- strings
- condicionais
- listas
- dicionários
- funções
- arquivos
- JSON
- pandas
- validação

Essas são as peças mínimas para entender como um agente funciona por dentro.

Na próxima etapa, essas peças viram uma arquitetura completa com:

- `agent.py`
- `tools.py`
- `prompts.py`
- `state.py`
- `memory.py`
- arquivos `.md` de contexto

**Na próxima aula, juntamos tudo isso para construir um agente de IA de verdade.**